DROP TABLE IF EXISTS paper_contents CASCADE;
DROP TABLE IF EXISTS papers CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS entity_members CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS workspaces CASCADE;
DROP TABLE IF EXISTS users CASCADE;
