export const PRIVATE = {
  ME: "/private/users/me",
  USER_PROVISION: "/private/users/provision",
  LIST_WORKSPACES: "/private/workspaces/list",
  WORKSPACE_ACTIVE: "/private/workspaces/active",
  DASHBOARD_PROJECTS: "/private/dashboard/projects",
  DASHBOARD_PAPERS: "/private/dashboard/papers",
  DASHBOARD_MEMBERS: "/private/dashboard/members",
  DASHBOARD_WORKSPACES: "/private/dashboard/workspaces",
  PROJECT_COLLECTIONS: "/private/dashboard/projects",
  PROJECT_PAPERS: "/private/dashboard/projects",
  COLLECTION_PAPERS: "/private/dashboard/collections",
  PROJECT_BY_ID: "/private/projects/id",
  PROJECT_BY_SLUG: "/private/projects/slug",
  PROJECT_CREATE: "/private/projects/create",
  PROJECT_CHECK_SLUG: "/private/projects/check-slug",
  COLLECTION_BY_ID: "/private/collections/id",
  COLLECTION_BY_SLUG: "/private/collections/slug",
  PAPER_BY_ID: "/private/papers/id",
  PAPER_BY_SLUG: "/private/papers/slug",
  PAPER_CREATE: "/private/papers/create",
  PAPER_SAVE: "/private/papers/save",
  PAPER_REMOVE_THUMBNAIL: "/private/papers/remove-thumbnail",
  PAPER_UPLOAD_THUMBNAIL: "/private/papers/upload-thumbnail",
  PAPER_UPLOAD_IMAGE: "/private/papers/upload-embedded-image",
  SCREEN_WORKSPACE: "/private/screen/workspace",
  SCREEN_PROJECT: "/private/screen/project",
  SCREEN_COLLECTION: "/private/screen/collection",
} as const;

export const PUBLIC = {} as const;
